on:
  push:
    branches: [main]
jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - uses: tokghwt/my-js-action@v0
        with:
          pattern: '^(?:feat|fix|release|chore)(?:\([^)]+\))?: [A-Z]'
