on:
  pull_request:
    types: [opened, edited]
  push:
    branches: [main]

jobs:
  commit_message_check:
    runs-on: ubuntu-latest
    steps:
      - uses: tokghwt/my-js-action@v0.11.0
        with:
          pattern: '^(?:feat|fix|release|chore)(?:\([^)]+\))?: [A-Z]'
