on:
  pull_request:
    types:
      - opened
      - edited
  pull_request_target:
    types:
      - opened
      - edited
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check action step
        id: checkstep
        uses: tokghwt/my-js-action@v0.5.0
        with:
          pattern: '^(?:feat|fix|release|chore): (?:#[1-9][0-9]*: )?[A-Z]'
